data:extend(
{
  {
    type = "string-setting",
    name = "tas-s-p-filename",
    setting_type = "runtime-global",
    default_value = "first-tas",
    allow_blank = false,
    order = "tas-s-p-a1",
  },
  {
    type = "int-setting",
    name = "tas-s-p-frequency",
    setting_type = "runtime-global",
    default_value = 5,
    minimum_value = 0,
    maximum_value = 120,
    order = "tas-s-p-a2",
  },
  {
    type = "bool-setting",
    name = "tas-s-p-reset",
    setting_type = "runtime-global",
    default_value = true,
    allow_blank = false,
    order = "tas-s-p-a3",
  },
  {
    type = "bool-setting",
    name = "tas-s-p-position",
    setting_type = "runtime-global",
    default_value = true,
    allow_blank = false,
    order = "tas-s-p-b2",
  },
  {
    type = "bool-setting",
    name = "tas-s-p-inventory",
    setting_type = "runtime-global",
    default_value = true,
    allow_blank = false,
    order = "tas-s-p-b3",
  },
  {
    type = "bool-setting",
    name = "tas-s-p-tech",
    setting_type = "runtime-global",
    default_value = false,
    allow_blank = false,
    order = "tas-s-p-b4",
  },
  {
    type = "bool-setting",
    name = "tas-s-p-craft",
    setting_type = "runtime-global",
    default_value = false,
    allow_blank = false,
    order = "tas-s-p-b5",
  },
})